version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '82:80'
      - '85:81'
      - '445:443'
    volumes:
      - /data/docker/nginx-proxy-manager:/data
      - /data/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
